[tool.poetry]
name = 'symbol-sakuya'
version = '0.1.0'
description = 'Symbol Sakuya node deployment tool'
authors = ['nemnesia <the.nemnesia@gmail.com>']
maintainers = ['nemnesia <the.nemnesia@gmail.com>']
license = 'MIT'

readme = 'README.md'

packages = [{ include = 'sakuya' }]

repository = 'https://github.com/symbol/product/tree/main/tools/konohanasakuya-hime'

keywords = ['symbol', 'sakuya', 'deployment', 'node']

classifiers = [
	'Programming Language :: Python :: 3.10',
	'Programming Language :: Python :: 3.11',
	'Programming Language :: Python :: 3.12',
	'Programming Language :: Python :: 3.13',
	'Programming Language :: Python :: 3.14'
]

include = ['sakuya/lang/*/LC_MESSAGES/messages.mo']

[tool.poetry.dependencies]
python = "^3.10"

[tool.pytest.ini_options]
asyncio_mode = 'auto'
filterwarnings = [
	"ignore:The 'warn' method is deprecated:DeprecationWarning"
]
